export const P = [
  {
    id: 1,
    title: "Two Sum",
    cat: "Array",
    diff: "Easy",
    lc: 1,
    pat: "Hash Map",
    desc: `Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.`,
    examples: [
      { input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "Because nums[0] + nums[1] == 9, we return [0, 1].", stdin: "[2,7,11,15]\n9" },
      { input: "nums = [3,2,4], target = 6", output: "[1,2]", stdin: "[3,2,4]\n6" },
      { input: "nums = [3,3], target = 6", output: "[0,1]", stdin: "[3,3]\n6" },
    ],
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "-10^9 <= target <= 10^9",
      "Only one valid answer exists.",
    ],
    sol: `def twoSum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        diff = target - n\n        if diff in seen: return [seen[diff], i]\n        seen[n] = i`,
    note: "One-pass hash map. Check complement before inserting. O(n) time, O(n) space.",
  },
  {
    id: 2,
    title: "Best Time to Buy & Sell Stock",
    cat: "Array",
    diff: "Easy",
    lc: 121,
    pat: "Sliding Window",
    desc: `You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.`,
    examples: [
      { input: "prices = [7,1,5,3,6,4]", output: "5", explanation: "Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6 - 1 = 5.", stdin: "[7,1,5,3,6,4]" },
      { input: "prices = [7,6,4,3,1]", output: "0", explanation: "In this case, no transactions are done and the max profit = 0.", stdin: "[7,6,4,3,1]" },
    ],
    constraints: [
      "1 <= prices.length <= 10^5",
      "0 <= prices[i] <= 10^4",
    ],
    sol: `def maxProfit(prices):\n    l, r = 0, 1\n    maxP = 0\n    while r < len(prices):\n        if prices[l] < prices[r]: maxP = max(maxP, prices[r]-prices[l])\n        else: l = r\n        r += 1\n    return maxP`,
    note: "Two pointer: left=buy, right=sell. Move l to r when prices[l]≥prices[r]. O(n).",
  },
  {
    id: 3,
    title: "Contains Duplicate",
    cat: "Array",
    diff: "Easy",
    lc: 217,
    pat: "Hash Set",
    desc: `Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.`,
    examples: [
      { input: "nums = [1,2,3,1]", output: "true", stdin: "[1,2,3,1]" },
      { input: "nums = [1,2,3,4]", output: "false", stdin: "[1,2,3,4]" },
      { input: "nums = [1,1,1,3,3,4,3,2,4,2]", output: "true", stdin: "[1,1,1,3,3,4,3,2,4,2]" },
    ],
    constraints: [
      "1 <= nums.length <= 10^5",
      "-10^9 <= nums[i] <= 10^9",
    ],
    sol: `def containsDuplicate(nums):\n    return len(nums) != len(set(nums))`,
    note: "Set deduplicates. Length mismatch → duplicate exists. O(n).",
  },
  {
    id: 4,
    title: "Product of Array Except Self",
    cat: "Array",
    diff: "Medium",
    lc: 238,
    pat: "Prefix/Suffix",
    desc: `Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i]. The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer. You must write an algorithm that runs in O(n) time and without using the division operation.`,
    examples: [
      { input: "nums = [1,2,3,4]", output: "[24,12,8,6]", stdin: "[1,2,3,4]" },
      { input: "nums = [-1,1,0,-3,3]", output: "[0,0,9,0,0]", stdin: "[-1,1,0,-3,3]" },
    ],
    constraints: [
      "2 <= nums.length <= 10^5",
      "-30 <= nums[i] <= 30",
      "The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.",
    ],
    sol: `def productExceptSelf(nums):\n    res = [1]*len(nums)\n    pre = 1\n    for i in range(len(nums)): res[i]=pre; pre*=nums[i]\n    post = 1\n    for i in range(len(nums)-1,-1,-1): res[i]*=post; post*=nums[i]\n    return res`,
    note: "Two passes: prefix L→R, multiply postfix R→L. O(n) time, O(1) extra space.",
  },
  {
    id: 5,
    title: "Maximum Subarray",
    cat: "Array",
    diff: "Medium",
    lc: 53,
    pat: "Kadane's",
    desc: `Given an integer array nums, find the subarray with the largest sum, and return its sum.`,
    examples: [
      { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6", explanation: "The subarray [4,-1,2,1] has the largest sum 6.", stdin: "[-2,1,-3,4,-1,2,1,-5,4]" },
      { input: "nums = [1]", output: "1", stdin: "[1]" },
      { input: "nums = [5,4,-1,7,8]", output: "23", stdin: "[5,4,-1,7,8]" },
    ],
    constraints: [
      "1 <= nums.length <= 10^5",
      "-10^4 <= nums[i] <= 10^4",
    ],
    sol: `def maxSubArray(nums):\n    best = cur = nums[0]\n    for n in nums[1:]:\n        cur = max(n, cur+n)\n        best = max(best, cur)\n    return best`,
    note: "Kadane's: extend or restart at each element. O(n), O(1).",
  },
  {
    id: 6,
    title: "Maximum Product Subarray",
    cat: "Array",
    diff: "Medium",
    lc: 152,
    pat: "Dynamic Programming",
    desc: `Given an integer array nums, find a subarray that has the largest product, and return the product. The test cases are generated so that the answer will fit in a 32-bit integer.`,
    examples: [
      { input: "nums = [2,3,-2,4]", output: "6", explanation: "[2,3] has the largest product 6.", stdin: "[2,3,-2,4]" },
      { input: "nums = [-2,0,-1]", output: "0", explanation: "The result cannot be 2, because [-2,-1] is not a subarray.", stdin: "[-2,0,-1]" },
    ],
    constraints: [
      "1 <= nums.length <= 2 * 10^4",
      "-10 <= nums[i] <= 10",
      "The product of any subarray of nums is guaranteed to fit in a 32-bit integer.",
    ],
    sol: `def maxProduct(nums):\n    res = max(nums)\n    curMin = curMax = 1\n    for n in nums:\n        if n==0: curMin=curMax=1; continue\n        t = curMax*n\n        curMax = max(n*curMax,n*curMin,n)\n        curMin = min(t,n*curMin,n)\n        res = max(res,curMax)\n    return res`,
    note: "Track both max and min (neg×neg=pos). Reset on zero. O(n), O(1).",
  },
  {
    id: 7,
    title: "Find Min in Rotated Sorted Array",
    cat: "Array",
    diff: "Medium",
    lc: 153,
    pat: "Binary Search",
    desc: `Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array nums of unique elements, return the minimum element of this array. You must write an algorithm that runs in O(log n) time.`,
    examples: [
      { input: "nums = [3,4,5,1,2]", output: "1", explanation: "The original array was [1,2,3,4,5] rotated 3 times.", stdin: "[3,4,5,1,2]" },
      { input: "nums = [4,5,6,7,0,1,2]", output: "0", explanation: "The original array was [0,1,2,4,5,6,7] and it was rotated 4 times.", stdin: "[4,5,6,7,0,1,2]" },
      { input: "nums = [11,13,15,17]", output: "11", explanation: "The original array was [11,13,15,17] and it was rotated 4 times.", stdin: "[11,13,15,17]" },
    ],
    constraints: [
      "n == nums.length",
      "1 <= n <= 5000",
      "-5000 <= nums[i] <= 5000",
      "All the integers of nums are unique.",
      "nums is sorted and rotated between 1 and n times.",
    ],
    sol: `def findMin(nums):\n    l,r = 0,len(nums)-1\n    res = nums[0]\n    while l<=r:\n        if nums[l]<nums[r]: return min(res,nums[l])\n        m = (l+r)//2\n        res = min(res,nums[m])\n        if nums[m]>=nums[l]: l=m+1\n        else: r=m-1\n    return res`,
    note: "If mid≥left, min is in right half. O(log n).",
  },
  {
    id: 8,
    title: "Search in Rotated Sorted Array",
    cat: "Array",
    diff: "Medium",
    lc: 33,
    pat: "Binary Search",
    desc: `Given the array nums sorted in ascending order (with distinct values) that is possibly rotated at an unknown pivot index, and an integer target, return the index of target if it is in nums, or -1 if it is not in nums. You must write an algorithm with O(log n) runtime complexity.`,
    examples: [
      { input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4", stdin: "[4,5,6,7,0,1,2]\n0" },
      { input: "nums = [4,5,6,7,0,1,2], target = 3", output: "-1", stdin: "[4,5,6,7,0,1,2]\n3" },
      { input: "nums = [1], target = 0", output: "-1", stdin: "[1]\n0" },
    ],
    constraints: [
      "1 <= nums.length <= 5000",
      "-10^4 <= nums[i] <= 10^4",
      "All values of nums are unique.",
      "nums is an ascending array that is possibly rotated.",
      "-10^4 <= target <= 10^4",
    ],
    sol: `def search(nums, target):\n    l,r = 0,len(nums)-1\n    while l<=r:\n        m=(l+r)//2\n        if nums[m]==target: return m\n        if nums[l]<=nums[m]:\n            if target>nums[m] or target<nums[l]: l=m+1\n            else: r=m-1\n        else:\n            if target<nums[m] or target>nums[r]: r=m-1\n            else: l=m+1\n    return -1`,
    note: "One side always sorted. Check which, then narrow. O(log n).",
  },
  {
    id: 9,
    title: "3Sum",
    cat: "Array",
    diff: "Medium",
    lc: 15,
    pat: "Two Pointers",
    desc: `Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0. Notice that the solution set must not contain duplicate triplets.`,
    examples: [
      { input: "nums = [-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]", explanation: "nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0. nums[1] + nums[2] + nums[4] = 0 + 1 + (-1) = 0. nums[0] + nums[3] + nums[4] = (-1) + 2 + (-1) = 0.", stdin: "[-1,0,1,2,-1,-4]" },
      { input: "nums = [0,1,1]", output: "[]", stdin: "[0,1,1]" },
      { input: "nums = [0,0,0]", output: "[[0,0,0]]", stdin: "[0,0,0]" },
    ],
    constraints: [
      "3 <= nums.length <= 3000",
      "-10^5 <= nums[i] <= 10^5",
    ],
    sol: `def threeSum(nums):\n    res=[]; nums.sort()\n    for i,a in enumerate(nums):\n        if a>0: break\n        if i>0 and a==nums[i-1]: continue\n        l,r=i+1,len(nums)-1\n        while l<r:\n            s=a+nums[l]+nums[r]\n            if s>0: r-=1\n            elif s<0: l+=1\n            else:\n                res.append([a,nums[l],nums[r]]); l+=1\n                while nums[l]==nums[l-1] and l<r: l+=1\n    return res`,
    note: "Sort, fix one, two-pointer rest. Skip duplicates. O(n²).",
  },
  {
    id: 10,
    title: "Container With Most Water",
    cat: "Array",
    diff: "Medium",
    lc: 11,
    pat: "Two Pointers",
    desc: `You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.`,
    examples: [
      { input: "height = [1,8,6,2,5,4,8,3,7]", output: "49", explanation: "The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. The max area of water the container can contain is 49.", stdin: "[1,8,6,2,5,4,8,3,7]" },
      { input: "height = [1,1]", output: "1", stdin: "[1,1]" },
    ],
    constraints: [
      "n == height.length",
      "2 <= n <= 10^5",
      "0 <= height[i] <= 10^4",
    ],
    sol: `def maxArea(h):\n    l,r=0,len(h)-1; water=0\n    while l<r:\n        water=max(water,min(h[l],h[r])*(r-l))\n        if h[l]<h[r]: l+=1\n        else: r-=1\n    return water`,
    note: "Move shorter line inward — moving taller can only reduce. O(n).",
  },
  {
    id: 11,
    title: "Sum of Two Integers",
    cat: "Binary",
    diff: "Medium",
    lc: 371,
    pat: "Bit Manipulation",
    desc: `Given two integers a and b, return the sum of the two integers without using the operators + and -.`,
    examples: [
      { input: "a = 1, b = 2", output: "3", stdin: "1\n2" },
      { input: "a = 2, b = 3", output: "5", stdin: "2\n3" },
    ],
    constraints: [
      "-1000 <= a <= 1000",
      "-1000 <= b <= 1000",
    ],
    sol: `def getSum(a,b):\n    mask=0xFFFFFFFF\n    while b&mask:\n        carry=(a&b)<<1; a=a^b; b=carry\n    return a if b==0 else a&mask`,
    note: "XOR=add no carry, AND<<1=carry. Repeat until no carry. Mask for Python ints.",
  },
  {
    id: 12,
    title: "Number of 1 Bits",
    cat: "Binary",
    diff: "Easy",
    lc: 191,
    pat: "Bit Manipulation",
    desc: `Write a function that takes the binary representation of a positive integer and returns the number of set bits it has (also known as the Hamming weight).`,
    examples: [
      { input: "n = 11", output: "3", explanation: "The input binary string 1011 has a total of three set bits.", stdin: "11" },
      { input: "n = 128", output: "1", explanation: "The input binary string 10000000 has a total of one set bit.", stdin: "128" },
      { input: "n = 2147483645", output: "30", stdin: "2147483645" },
    ],
    constraints: [
      "1 <= n <= 2^31 - 1",
    ],
    sol: `def hammingWeight(n):\n    res=0\n    while n: n&=n-1; res+=1\n    return res`,
    note: "n&(n-1) clears lowest set bit. Count iterations. O(number of 1s).",
  },
  {
    id: 13,
    title: "Counting Bits",
    cat: "Binary",
    diff: "Easy",
    lc: 338,
    pat: "Dynamic Programming",
    desc: `Given an integer n, return an array ans of length n + 1 such that for each i (0 <= i <= n), ans[i] is the number of 1's in the binary representation of i.`,
    examples: [
      { input: "n = 2", output: "[0,1,1]", explanation: "0 --> 0, 1 --> 1, 2 --> 10", stdin: "2" },
      { input: "n = 5", output: "[0,1,1,2,1,2]", explanation: "0 --> 0, 1 --> 1, 2 --> 10, 3 --> 11, 4 --> 100, 5 --> 101", stdin: "5" },
    ],
    constraints: [
      "0 <= n <= 10^5",
    ],
    sol: `def countBits(n):\n    dp=[0]*(n+1); off=1\n    for i in range(1,n+1):\n        if off*2==i: off=i\n        dp[i]=1+dp[i-off]\n    return dp`,
    note: "dp[i]=1+dp[i-MSB]. Offset tracks current power of 2. O(n).",
  },
  {
    id: 14,
    title: "Missing Number",
    cat: "Binary",
    diff: "Easy",
    lc: 268,
    pat: "Bit Manipulation",
    desc: `Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing from the array.`,
    examples: [
      { input: "nums = [3,0,1]", output: "2", explanation: "n = 3 since there are 3 numbers, so all numbers are in the range [0,3]. 2 is the missing number.", stdin: "[3,0,1]" },
      { input: "nums = [0,1]", output: "2", explanation: "n = 2 since there are 2 numbers, so all numbers are in the range [0,2]. 2 is the missing number.", stdin: "[0,1]" },
      { input: "nums = [9,6,4,2,3,5,7,0,1]", output: "8", stdin: "[9,6,4,2,3,5,7,0,1]" },
    ],
    constraints: [
      "n == nums.length",
      "1 <= n <= 10^4",
      "0 <= nums[i] <= n",
      "All the numbers of nums are unique.",
    ],
    sol: `def missingNumber(nums):\n    res=len(nums)\n    for i,n in enumerate(nums): res^=i^n\n    return res`,
    note: "XOR all indices and values. Everything cancels except missing. O(n), O(1).",
  },
  {
    id: 15,
    title: "Reverse Bits",
    cat: "Binary",
    diff: "Easy",
    lc: 190,
    pat: "Bit Manipulation",
    desc: `Reverse bits of a given 32 bits unsigned integer.`,
    examples: [
      { input: "n = 00000010100101000001111010011100", output: "964176192 (00111001011110000010100101000000)", explanation: "The input binary string 00000010100101000001111010011100 represents the unsigned integer 43261596, so return 964176192 which its binary representation is 00111001011110000010100101000000.", stdin: "43261596" },
      { input: "n = 11111111111111111111111111111101", output: "3221225471 (10111111111111111111111111111111)", stdin: "4294967293" },
    ],
    constraints: [
      "The input must be a binary string of length 32.",
    ],
    sol: `def reverseBits(n):\n    res=0\n    for i in range(32): res|=((n>>i)&1)<<(31-i)\n    return res`,
    note: "Extract each bit R→L, place L→R. 32 iterations. O(1).",
  },
  {
    id: 16,
    title: "Climbing Stairs",
    cat: "DP",
    diff: "Easy",
    lc: 70,
    pat: "1-D DP",
    desc: `You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?`,
    examples: [
      { input: "n = 2", output: "2", explanation: "There are two ways to climb to the top: 1 step + 1 step, and 2 steps.", stdin: "2" },
      { input: "n = 3", output: "3", explanation: "There are three ways: 1+1+1, 1+2, and 2+1.", stdin: "3" },
    ],
    constraints: [
      "1 <= n <= 45",
    ],
    sol: `def climbStairs(n):\n    a,b=1,1\n    for _ in range(n-1): a,b=b,a+b\n    return b`,
    note: "Fibonacci. ways(n)=ways(n-1)+ways(n-2). Two vars. O(n), O(1).",
  },
  {
    id: 17,
    title: "Coin Change",
    cat: "DP",
    diff: "Medium",
    lc: 322,
    pat: "1-D DP",
    desc: `You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money. Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1. You may assume that you have an infinite number of each kind of coin.`,
    examples: [
      { input: "coins = [1,2,5], amount = 11", output: "3", explanation: "11 = 5 + 5 + 1", stdin: "[1,2,5]\n11" },
      { input: "coins = [2], amount = 3", output: "-1", stdin: "[2]\n3" },
      { input: "coins = [1], amount = 0", output: "0", stdin: "[1]\n0" },
    ],
    constraints: [
      "1 <= coins.length <= 12",
      "1 <= coins[i] <= 2^31 - 1",
      "0 <= amount <= 10^4",
    ],
    sol: `def coinChange(coins,amount):\n    dp=[float('inf')]*(amount+1); dp[0]=0\n    for a in range(1,amount+1):\n        for c in coins:\n            if a-c>=0: dp[a]=min(dp[a],1+dp[a-c])\n    return dp[amount] if dp[amount]!=float('inf') else -1`,
    note: "dp[a]=min coins for amount a. Build from 0 up. O(amount×coins).",
  },
  {
    id: 18,
    title: "Longest Increasing Subsequence",
    cat: "DP",
    diff: "Medium",
    lc: 300,
    pat: "1-D DP",
    desc: `Given an integer array nums, return the length of the longest strictly increasing subsequence.`,
    examples: [
      { input: "nums = [10,9,2,5,3,7,101,18]", output: "4", explanation: "The longest increasing subsequence is [2,3,7,101], therefore the length is 4.", stdin: "[10,9,2,5,3,7,101,18]" },
      { input: "nums = [0,1,0,3,2,3]", output: "4", stdin: "[0,1,0,3,2,3]" },
      { input: "nums = [7,7,7,7,7,7,7]", output: "1", stdin: "[7,7,7,7,7,7,7]" },
    ],
    constraints: [
      "1 <= nums.length <= 2500",
      "-10^4 <= nums[i] <= 10^4",
    ],
    sol: `def lengthOfLIS(nums):\n    dp=[1]*len(nums)\n    for i in range(1,len(nums)):\n        for j in range(i):\n            if nums[j]<nums[i]: dp[i]=max(dp[i],dp[j]+1)\n    return max(dp)`,
    note: "dp[i]=LIS ending at i. O(n²). Binary search variant is O(n log n).",
  },
  {
    id: 19,
    title: "Longest Common Subsequence",
    cat: "DP",
    diff: "Medium",
    lc: 1143,
    pat: "2-D DP",
    desc: `Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0. A subsequence of a string is a new string generated from the original string with some characters (can be none) deleted without changing the relative order of the remaining characters.`,
    examples: [
      { input: "text1 = \"abcde\", text2 = \"ace\"", output: "3", explanation: "The longest common subsequence is \"ace\" and its length is 3.", stdin: "abcde\nace" },
      { input: "text1 = \"abc\", text2 = \"abc\"", output: "3", explanation: "The longest common subsequence is \"abc\" and its length is 3.", stdin: "abc\nabc" },
      { input: "text1 = \"abc\", text2 = \"def\"", output: "0", explanation: "There is no such common subsequence, so the result is 0.", stdin: "abc\ndef" },
    ],
    constraints: [
      "1 <= text1.length, text2.length <= 1000",
      "text1 and text2 consist of only lowercase English characters.",
    ],
    sol: `def longestCommonSubsequence(t1,t2):\n    dp=[[0]*(len(t2)+1) for _ in range(len(t1)+1)]\n    for i in range(len(t1)-1,-1,-1):\n        for j in range(len(t2)-1,-1,-1):\n            if t1[i]==t2[j]: dp[i][j]=1+dp[i+1][j+1]\n            else: dp[i][j]=max(dp[i+1][j],dp[i][j+1])\n    return dp[0][0]`,
    note: "2D DP: match→diagonal+1, else→max(down,right). O(m×n).",
  },
  {
    id: 20,
    title: "Word Break",
    cat: "DP",
    diff: "Medium",
    lc: 139,
    pat: "1-D DP",
    desc: `Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words. Note that the same word in the dictionary may be reused multiple times in the segmentation.`,
    examples: [
      { input: "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", output: "true", explanation: "Return true because \"leetcode\" can be segmented as \"leet code\".", stdin: "leetcode\n[\"leet\",\"code\"]" },
      { input: "s = \"applepenapple\", wordDict = [\"apple\",\"pen\"]", output: "true", explanation: "Return true because \"applepenapple\" can be segmented as \"apple pen apple\".", stdin: "applepenapple\n[\"apple\",\"pen\"]" },
      { input: "s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]", output: "false", stdin: "catsandog\n[\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]" },
    ],
    constraints: [
      "1 <= s.length <= 300",
      "1 <= wordDict.length <= 1000",
      "1 <= wordDict[i].length <= 20",
      "s and wordDict[i] consist of only lowercase English letters.",
      "All the strings of wordDict are unique.",
    ],
    sol: `def wordBreak(s,wordDict):\n    dp=[False]*(len(s)+1); dp[len(s)]=True\n    for i in range(len(s)-1,-1,-1):\n        for w in wordDict:\n            if i+len(w)<=len(s) and s[i:i+len(w)]==w: dp[i]=dp[i+len(w)]\n            if dp[i]: break\n    return dp[0]`,
    note: "dp[i]=can segment s[i:]. Work backwards. O(n×W×w).",
  },
  {
    id: 21,
    title: "Combination Sum IV",
    cat: "DP",
    diff: "Medium",
    lc: 377,
    pat: "1-D DP",
    desc: `Given an array of distinct integers nums and a target integer target, return the number of possible combinations that add up to target. The test cases are generated so that the answer can fit in a 32-bit integer. Note that different sequences are counted as different combinations.`,
    examples: [
      { input: "nums = [1,2,3], target = 4", output: "7", explanation: "The possible combination ways are: (1,1,1,1), (1,1,2), (1,2,1), (1,3), (2,1,1), (2,2), (3,1). Note that different sequences are counted as different combinations.", stdin: "[1,2,3]\n4" },
      { input: "nums = [9], target = 3", output: "0", stdin: "[9]\n3" },
    ],
    constraints: [
      "1 <= nums.length <= 200",
      "1 <= nums[i] <= 1000",
      "All the elements of nums are unique.",
      "1 <= target <= 1000",
    ],
    sol: `def combinationSum4(nums,target):\n    dp={0:1}\n    for t in range(1,target+1): dp[t]=sum(dp.get(t-n,0) for n in nums)\n    return dp[target]`,
    note: "dp[t]=ways to make t. Order matters→loop amount outer. O(target×n).",
  },
  {
    id: 22,
    title: "House Robber",
    cat: "DP",
    diff: "Medium",
    lc: 198,
    pat: "1-D DP",
    desc: `You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. The only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night. Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.`,
    examples: [
      { input: "nums = [1,2,3,1]", output: "4", explanation: "Rob house 1 (money = 1) and then rob house 3 (money = 3). Total amount you can rob = 1 + 3 = 4.", stdin: "[1,2,3,1]" },
      { input: "nums = [2,7,9,3,1]", output: "12", explanation: "Rob house 1 (money = 2), rob house 3 (money = 9) and rob house 5 (money = 1). Total amount = 2 + 9 + 1 = 12.", stdin: "[2,7,9,3,1]" },
    ],
    constraints: [
      "1 <= nums.length <= 100",
      "0 <= nums[i] <= 400",
    ],
    sol: `def rob(nums):\n    a,b=0,0\n    for n in nums: a,b=b,max(n+a,b)\n    return b`,
    note: "max(skip=b, take=n+a). Two vars. O(n), O(1).",
  },
  {
    id: 23,
    title: "House Robber II",
    cat: "DP",
    diff: "Medium",
    lc: 213,
    pat: "1-D DP",
    desc: `You are a professional robber planning to rob houses along a street. All houses at this place are arranged in a circle. Given an integer array nums representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police. Adjacent houses (including first and last) cannot both be robbed.`,
    examples: [
      { input: "nums = [2,3,2]", output: "3", explanation: "You cannot rob house 1 (money = 2) and then rob house 3 (money = 2), because they are adjacent houses.", stdin: "[2,3,2]" },
      { input: "nums = [1,2,3,1]", output: "4", explanation: "Rob house 1 (money = 1) and then rob house 3 (money = 3). Total = 4.", stdin: "[1,2,3,1]" },
      { input: "nums = [1,2,3]", output: "3", stdin: "[1,2,3]" },
    ],
    constraints: [
      "1 <= nums.length <= 100",
      "0 <= nums[i] <= 1000",
    ],
    sol: `def rob(nums):\n    def h(a):\n        r1=r2=0\n        for n in a: r1,r2=r2,max(n+r1,r2)\n        return r2\n    return max(nums[0],h(nums[:-1]),h(nums[1:]))`,
    note: "Run House Robber I twice: skip first, skip last. Take max. O(n).",
  },
  {
    id: 24,
    title: "Decode Ways",
    cat: "DP",
    diff: "Medium",
    lc: 91,
    pat: "1-D DP",
    desc: `A message containing letters from A-Z can be encoded into numbers using 'A' -> "1", 'B' -> "2", ..., 'Z' -> "26". Given a string s containing only digits, return the number of ways to decode it.`,
    examples: [
      { input: "s = \"12\"", output: "2", explanation: "\"12\" could be decoded as \"AB\" (1 2) or \"L\" (12).", stdin: "12" },
      { input: "s = \"226\"", output: "3", explanation: "\"226\" could be decoded as \"BZ\" (2 26), \"VF\" (22 6), or \"BBF\" (2 2 6).", stdin: "226" },
      { input: "s = \"06\"", output: "0", explanation: "\"06\" cannot be mapped to \"F\" because of the leading zero.", stdin: "06" },
    ],
    constraints: [
      "1 <= s.length <= 100",
      "s contains only digits and may contain leading zeros.",
    ],
    sol: `def numDecodings(s):\n    dp={len(s):1}\n    def f(i):\n        if i in dp: return dp[i]\n        if s[i]=='0': return 0\n        r=f(i+1)\n        if i+1<len(s) and (s[i]=='1' or s[i]=='2' and s[i+1]<'7'): r+=f(i+2)\n        dp[i]=r; return r\n    return f(0)`,
    note: "Memoized DFS. Single (if !=0) or two digits (10-26). O(n).",
  },
  {
    id: 25,
    title: "Unique Paths",
    cat: "DP",
    diff: "Medium",
    lc: 62,
    pat: "2-D DP",
    desc: `There is a robot on an m x n grid. The robot is initially located at the top-left corner and tries to move to the bottom-right corner. The robot can only move either down or right at any point in time. Given the two integers m and n, return the number of possible unique paths that the robot can take to reach the bottom-right corner.`,
    examples: [
      { input: "m = 3, n = 7", output: "28", stdin: "3\n7" },
      { input: "m = 3, n = 2", output: "3", explanation: "From the top-left corner, there are a total of 3 ways to reach the bottom-right corner: right→down→down, down→right→down, down→down→right.", stdin: "3\n2" },
    ],
    constraints: [
      "1 <= m, n <= 100",
    ],
    sol: `def uniquePaths(m,n):\n    row=[1]*n\n    for _ in range(m-1):\n        nr=[1]*n\n        for j in range(n-2,-1,-1): nr[j]=nr[j+1]+row[j]\n        row=nr\n    return row[0]`,
    note: "Bottom row=1s. Each cell=right+below. One row at a time. O(m×n), O(n).",
  },
  {
    id: 26,
    title: "Jump Game",
    cat: "DP",
    diff: "Medium",
    lc: 55,
    pat: "Greedy",
    desc: `You are given an integer array nums. You are initially positioned at the first index, and each element in the array represents your maximum jump length at that position. Return true if you can reach the last index, or false otherwise.`,
    examples: [
      { input: "nums = [2,3,1,1,4]", output: "true", explanation: "Jump 1 step from index 0 to 1, then 3 steps to the last index.", stdin: "[2,3,1,1,4]" },
      { input: "nums = [3,2,1,0,4]", output: "false", explanation: "You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.", stdin: "[3,2,1,0,4]" },
    ],
    constraints: [
      "1 <= nums.length <= 10^4",
      "0 <= nums[i] <= 10^5",
    ],
    sol: `def canJump(nums):\n    goal=len(nums)-1\n    for i in range(len(nums)-2,-1,-1):\n        if i+nums[i]>=goal: goal=i\n    return goal==0`,
    note: "Work backwards. Shift goal when reachable. O(n), O(1).",
  },
  {
    id: 27,
    title: "Clone Graph",
    cat: "Graph",
    diff: "Medium",
    lc: 133,
    pat: "DFS + Hash Map",
    desc: `Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph. Each node in the graph contains a value (int) and a list of its neighbors.`,
    examples: [
      { input: "adjList = [[2,4],[1,3],[2,4],[1,3]]", output: "[[2,4],[1,3],[2,4],[1,3]]", explanation: "There are 4 nodes in the graph. Node 1's neighbors are nodes 2 and 4. Node 2's neighbors are nodes 1 and 3. Node 3's neighbors are nodes 2 and 4. Node 4's neighbors are nodes 1 and 3.", stdin: "[[2,4],[1,3],[2,4],[1,3]]" },
      { input: "adjList = [[]]", output: "[[]]", explanation: "Note that the input contains one empty list. The graph consists of only one node with val = 1 and it does not have any neighbors.", stdin: "[[]]" },
      { input: "adjList = []", output: "[]", explanation: "This an empty graph, it does not have any nodes.", stdin: "[]" },
    ],
    constraints: [
      "The number of nodes in the graph is in the range [0, 100].",
      "1 <= Node.val <= 100",
      "Node.val is unique for each node.",
      "There are no repeated edges and no self-loops in the graph.",
    ],
    sol: `def cloneGraph(node):\n    m={}\n    def dfs(n):\n        if n in m: return m[n]\n        c=Node(n.val); m[n]=c\n        for nei in n.neighbors: c.neighbors.append(dfs(nei))\n        return c\n    return dfs(node) if node else None`,
    note: "DFS with old→new map. Store clone before recursing to handle cycles. O(V+E).",
  },
  {
    id: 28,
    title: "Course Schedule",
    cat: "Graph",
    diff: "Medium",
    lc: 207,
    pat: "Topological Sort",
    desc: `There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return true if you can finish all courses, otherwise return false.`,
    examples: [
      { input: "numCourses = 2, prerequisites = [[1,0]]", output: "true", explanation: "There are 2 courses to take. To take course 1 you should have finished course 0. So it is possible.", stdin: "2\n[[1,0]]" },
      { input: "numCourses = 2, prerequisites = [[1,0],[0,1]]", output: "false", explanation: "There are 2 courses to take. To take course 1 you should have finished course 0, and to take course 0 you should also have finished course 1. So it is impossible.", stdin: "2\n[[1,0],[0,1]]" },
    ],
    constraints: [
      "1 <= numCourses <= 2000",
      "0 <= prerequisites.length <= 5000",
      "prerequisites[i].length == 2",
      "0 <= ai, bi < numCourses",
      "All the pairs prerequisites[i] are unique.",
    ],
    sol: `def canFinish(n,pre):\n    adj=[[] for _ in range(n)]\n    for a,b in pre: adj[a].append(b)\n    vis={}\n    def dfs(c):\n        if c in vis: return vis[c]\n        vis[c]=True\n        for p in adj[c]:\n            if dfs(p): return True\n        vis[c]=False; adj[c]=[]\n        return False\n    return not any(dfs(c) for c in range(n))`,
    note: "DFS cycle detection. vis[c]=True means in current path. O(V+E).",
  },
  {
    id: 29,
    title: "Pacific Atlantic Water Flow",
    cat: "Graph",
    diff: "Medium",
    lc: 417,
    pat: "Multi-source DFS",
    desc: `There is an m x n rectangular island that borders both the Pacific Ocean and Atlantic Ocean. The Pacific Ocean touches the island's left and top edges, and the Atlantic Ocean touches the island's right and bottom edges. Water can only flow to neighboring cells with height equal or lower. Return a list of grid coordinates where water can flow to both the Pacific and Atlantic oceans.`,
    examples: [
      { input: "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", output: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]", stdin: "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]" },
      { input: "heights = [[1]]", output: "[[0,0]]", stdin: "[[1]]" },
    ],
    constraints: [
      "m == heights.length",
      "n == heights[r].length",
      "1 <= m, n <= 200",
      "0 <= heights[r][c] <= 10^5",
    ],
    sol: `def pacificAtlantic(h):\n    R,C=len(h),len(h[0]); pac=set(); atl=set()\n    def dfs(r,c,vis,prev):\n        if (r,c) in vis or r<0 or c<0 or r==R or c==C or h[r][c]<prev: return\n        vis.add((r,c))\n        for dr,dc in[(1,0),(-1,0),(0,1),(0,-1)]: dfs(r+dr,c+dc,vis,h[r][c])\n    for r in range(R): dfs(r,0,pac,h[r][0]); dfs(r,C-1,atl,h[r][C-1])\n    for c in range(C): dfs(0,c,pac,h[0][c]); dfs(R-1,c,atl,h[R-1][c])\n    return [[r,c] for r in range(R) for c in range(C) if (r,c) in pac and (r,c) in atl]`,
    note: "Flood inward from borders (reversed ≥). Intersection=answer. O(m×n).",
  },
  {
    id: 30,
    title: "Number of Islands",
    cat: "Graph",
    diff: "Medium",
    lc: 200,
    pat: "BFS/DFS",
    desc: `Given an m x n 2D binary grid which represents a map of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.`,
    examples: [
      { input: "grid = [[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]", output: "1", stdin: "[[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]" },
      { input: "grid = [[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"1\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"1\",\"1\"]]", output: "3", stdin: "[[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"1\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"1\",\"1\"]]" },
    ],
    constraints: [
      "m == grid.length",
      "n == grid[i].length",
      "1 <= m, n <= 300",
      "grid[i][j] is '0' or '1'.",
    ],
    sol: `def numIslands(grid):\n    R,C=len(grid),len(grid[0]); vis=set(); cnt=0\n    def bfs(r,c):\n        q=[(r,c)]; vis.add((r,c))\n        while q:\n            r,c=q.pop()\n            for dr,dc in[(1,0),(-1,0),(0,1),(0,-1)]:\n                nr,nc=r+dr,c+dc\n                if 0<=nr<R and 0<=nc<C and grid[nr][nc]=='1' and (nr,nc) not in vis:\n                    vis.add((nr,nc)); q.append((nr,nc))\n    for r in range(R):\n        for c in range(C):\n            if grid[r][c]=='1' and (r,c) not in vis: bfs(r,c); cnt+=1\n    return cnt`,
    note: "BFS from each unvisited '1'. Count BFS calls. O(m×n).",
  },
  {
    id: 31,
    title: "Longest Consecutive Sequence",
    cat: "Graph",
    diff: "Medium",
    lc: 128,
    pat: "Hash Set",
    desc: `Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence. You must write an algorithm that runs in O(n) time.`,
    examples: [
      { input: "nums = [100,4,200,1,3,2]", output: "4", explanation: "The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.", stdin: "[100,4,200,1,3,2]" },
      { input: "nums = [0,3,7,2,5,8,4,6,0,1]", output: "9", stdin: "[0,3,7,2,5,8,4,6,0,1]" },
    ],
    constraints: [
      "0 <= nums.length <= 10^5",
      "-10^9 <= nums[i] <= 10^9",
    ],
    sol: `def longestConsecutive(nums):\n    s=set(nums); best=0\n    for n in s:\n        if n-1 not in s:\n            l=1\n            while n+l in s: l+=1\n            best=max(best,l)\n    return best`,
    note: "Only count from sequence starts (n-1 not in set). O(n) amortized.",
  },
  {
    id: 32,
    title: "Alien Dictionary",
    cat: "Graph",
    diff: "Hard",
    lc: 269,
    pat: "Topological Sort",
    desc: `There is a new alien language that uses the English alphabet. However, the order among the letters is unknown. You are given a list of strings words from the alien language's dictionary, where the strings in words are sorted lexicographically by the rules of this new language. Return a string of the unique letters in the new alien language sorted in lexicographically increasing order by the new language's rules. If there is no solution, return "". If there are multiple solutions, return any of them.`,
    examples: [
      { input: "words = [\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]", output: "\"wertf\"", stdin: "[\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]" },
      { input: "words = [\"z\",\"x\"]", output: "\"zx\"", stdin: "[\"z\",\"x\"]" },
      { input: "words = [\"z\",\"x\",\"z\"]", output: "\"\"", explanation: "The order is invalid, so return \"\".", stdin: "[\"z\",\"x\",\"z\"]" },
    ],
    constraints: [
      "1 <= words.length <= 100",
      "1 <= words[i].length <= 100",
      "words[i] consists of only lowercase English letters.",
    ],
    sol: `def alienOrder(words):\n    adj={c:set() for w in words for c in w}\n    for i in range(len(words)-1):\n        w1,w2=words[i],words[i+1]; mn=min(len(w1),len(w2))\n        if len(w1)>len(w2) and w1[:mn]==w2[:mn]: return ''\n        for j in range(mn):\n            if w1[j]!=w2[j]: adj[w1[j]].add(w2[j]); break\n    vis={}; res=[]\n    def dfs(c):\n        if c in vis: return vis[c]\n        vis[c]=True\n        for n in adj[c]:\n            if dfs(n): return True\n        vis[c]=False; res.append(c)\n    for c in adj:\n        if dfs(c): return ''\n    return ''.join(reversed(res))`,
    note: "Build graph from adjacent word pairs. DFS topo sort. O(C+E).",
  },
  {
    id: 33,
    title: "Graph Valid Tree",
    cat: "Graph",
    diff: "Medium",
    lc: 261,
    pat: "Union Find",
    desc: `You have a graph of n nodes labeled from 0 to n - 1. You are given an integer n and a list of edges where edges[i] = [ai, bi] indicates that there is an undirected edge between nodes ai and bi in the graph. Return true if the edges of the given graph make up a valid tree, and false otherwise.`,
    examples: [
      { input: "n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]", output: "true", stdin: "5\n[[0,1],[0,2],[0,3],[1,4]]" },
      { input: "n = 5, edges = [[0,1],[1,2],[2,3],[1,3],[1,4]]", output: "false", stdin: "5\n[[0,1],[1,2],[2,3],[1,3],[1,4]]" },
    ],
    constraints: [
      "1 <= n <= 2000",
      "0 <= edges.length <= 5000",
      "edges[i].length == 2",
      "0 <= ai, bi < n",
      "There are no self-loops or repeated edges.",
    ],
    sol: `def validTree(n,edges):\n    if len(edges)!=n-1: return False\n    adj=[[] for _ in range(n)]\n    for a,b in edges: adj[a].append(b); adj[b].append(a)\n    vis=set()\n    def dfs(v,p):\n        if v in vis: return False\n        vis.add(v)\n        return all(dfs(u,v) for u in adj[v] if u!=p)\n    return dfs(0,-1) and len(vis)==n`,
    note: "Tree = n-1 edges + connected + no cycles. Check count first. O(V+E).",
  },
  {
    id: 34,
    title: "Number of Connected Components",
    cat: "Graph",
    diff: "Medium",
    lc: 323,
    pat: "Union Find",
    desc: `You have a graph of n nodes. You are given an integer n and an array edges where edges[i] = [ai, bi] indicates that there is an edge between ai and bi in the graph. Return the number of connected components in the graph.`,
    examples: [
      { input: "n = 5, edges = [[0,1],[1,2],[3,4]]", output: "2", stdin: "5\n[[0,1],[1,2],[3,4]]" },
      { input: "n = 5, edges = [[0,1],[1,2],[2,3],[3,4]]", output: "1", stdin: "5\n[[0,1],[1,2],[2,3],[3,4]]" },
    ],
    constraints: [
      "1 <= n <= 2000",
      "1 <= edges.length <= 5000",
      "edges[i].length == 2",
      "0 <= ai, bi < n",
      "ai != bi",
      "There are no repeated edges.",
    ],
    sol: `def countComponents(n,edges):\n    p=list(range(n)); r=[1]*n\n    def find(x):\n        while x!=p[x]: p[x]=p[p[x]]; x=p[x]\n        return x\n    def union(a,b):\n        a,b=find(a),find(b)\n        if a==b: return 0\n        if r[b]>r[a]: a,b=b,a\n        p[b]=a; r[a]+=r[b]; return 1\n    return n-sum(union(a,b) for a,b in edges)`,
    note: "Union-Find with path compression. Each union reduces count by 1. O(n·α(n)).",
  },
  {
    id: 35,
    title: "Insert Interval",
    cat: "Interval",
    diff: "Medium",
    lc: 57,
    pat: "Intervals",
    desc: `You are given an array of non-overlapping intervals sorted in ascending order by start time, and a newInterval to insert. Insert newInterval into intervals, merging if necessary, so that the result is still sorted and non-overlapping. Return the resulting array of intervals.`,
    examples: [
      { input: "intervals = [[1,3],[6,9]], newInterval = [2,5]", output: "[[1,5],[6,9]]", stdin: "[[1,3],[6,9]]\n[2,5]" },
      { input: "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]", output: "[[1,2],[3,10],[12,16]]", explanation: "Because the new interval [4,8] overlaps with [3,5],[6,7],[8,10].", stdin: "[[1,2],[3,5],[6,7],[8,10],[12,16]]\n[4,8]" },
    ],
    constraints: [
      "0 <= intervals.length <= 10^4",
      "intervals[i].length == 2",
      "0 <= starti <= endi <= 10^5",
      "intervals is sorted by starti in ascending order.",
      "newInterval.length == 2",
    ],
    sol: `def insert(intervals,new):\n    res=[]\n    for i,(s,e) in enumerate(intervals):\n        if new[1]<s: res.append(new); return res+intervals[i:]\n        elif new[0]>e: res.append([s,e])\n        else: new=[min(new[0],s),max(new[1],e)]\n    res.append(new); return res`,
    note: "Three cases: before, after, overlap→merge. O(n).",
  },
  {
    id: 36,
    title: "Merge Intervals",
    cat: "Interval",
    diff: "Medium",
    lc: 56,
    pat: "Intervals",
    desc: `Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.`,
    examples: [
      { input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]", explanation: "Since intervals [1,3] and [2,6] overlap, merge them into [1,6].", stdin: "[[1,3],[2,6],[8,10],[15,18]]" },
      { input: "intervals = [[1,4],[4,5]]", output: "[[1,5]]", explanation: "Intervals [1,4] and [4,5] are considered overlapping.", stdin: "[[1,4],[4,5]]" },
    ],
    constraints: [
      "1 <= intervals.length <= 10^4",
      "intervals[i].length == 2",
      "0 <= starti <= endi <= 10^4",
    ],
    sol: `def merge(intervals):\n    intervals.sort(key=lambda x:x[0]); res=[intervals[0]]\n    for s,e in intervals[1:]:\n        if s<=res[-1][1]: res[-1][1]=max(res[-1][1],e)\n        else: res.append([s,e])\n    return res`,
    note: "Sort by start. Overlap→extend, else append. O(n log n).",
  },
  {
    id: 37,
    title: "Non-overlapping Intervals",
    cat: "Interval",
    diff: "Medium",
    lc: 435,
    pat: "Greedy",
    desc: `Given an array of intervals intervals where intervals[i] = [starti, endi], return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.`,
    examples: [
      { input: "intervals = [[1,2],[2,3],[3,4],[1,3]]", output: "1", explanation: "[1,3] can be removed and the rest of the intervals are non-overlapping.", stdin: "[[1,2],[2,3],[3,4],[1,3]]" },
      { input: "intervals = [[1,2],[1,2],[1,2]]", output: "2", explanation: "You need to remove two [1,2] to make the rest of the intervals non-overlapping.", stdin: "[[1,2],[1,2],[1,2]]" },
      { input: "intervals = [[1,2],[2,3]]", output: "0", explanation: "You don't need to remove any of the intervals since they're already non-overlapping.", stdin: "[[1,2],[2,3]]" },
    ],
    constraints: [
      "1 <= intervals.length <= 10^5",
      "intervals[i].length == 2",
      "-5 * 10^4 <= starti < endi <= 5 * 10^4",
    ],
    sol: `def eraseOverlapIntervals(intervals):\n    intervals.sort(); res=0; end=intervals[0][1]\n    for s,e in intervals[1:]:\n        if s>=end: end=e\n        else: res+=1; end=min(end,e)\n    return res`,
    note: "Sort. On overlap remove the one with larger end (greedy). O(n log n).",
  },
  {
    id: 38,
    title: "Meeting Rooms",
    cat: "Interval",
    diff: "Easy",
    lc: 252,
    pat: "Intervals",
    desc: `Given an array of meeting time intervals where intervals[i] = [starti, endi], determine if a person could attend all meetings.`,
    examples: [
      { input: "intervals = [[0,30],[5,10],[15,20]]", output: "false", stdin: "[[0,30],[5,10],[15,20]]" },
      { input: "intervals = [[7,10],[2,4]]", output: "true", stdin: "[[7,10],[2,4]]" },
    ],
    constraints: [
      "0 <= intervals.length <= 10^4",
      "intervals[i].length == 2",
      "0 <= starti < endi <= 10^6",
    ],
    sol: `def canAttendMeetings(intervals):\n    intervals.sort(key=lambda x:x[0])\n    for i in range(1,len(intervals)):\n        if intervals[i][0]<intervals[i-1][1]: return False\n    return True`,
    note: "Sort by start. Any overlap→false. O(n log n).",
  },
  {
    id: 39,
    title: "Meeting Rooms II",
    cat: "Interval",
    diff: "Medium",
    lc: 253,
    pat: "Heap",
    desc: `Given an array of meeting time intervals intervals where intervals[i] = [starti, endi], return the minimum number of conference rooms required.`,
    examples: [
      { input: "intervals = [[0,30],[5,10],[15,20]]", output: "2", stdin: "[[0,30],[5,10],[15,20]]" },
      { input: "intervals = [[7,10],[2,4]]", output: "1", stdin: "[[7,10],[2,4]]" },
    ],
    constraints: [
      "1 <= intervals.length <= 10^4",
      "0 <= starti < endi <= 10^6",
    ],
    sol: `import heapq\ndef minMeetingRooms(intervals):\n    intervals.sort(key=lambda x:x[0]); h=[]\n    for s,e in intervals:\n        if h and h[0]<=s: heapq.heapreplace(h,e)\n        else: heapq.heappush(h,e)\n    return len(h)`,
    note: "Min-heap of end times. Reuse if free. Heap size=rooms. O(n log n).",
  },
  {
    id: 40,
    title: "Reverse Linked List",
    cat: "Linked List",
    diff: "Easy",
    lc: 206,
    pat: "Linked List",
    desc: `Given the head of a singly linked list, reverse the list, and return the reversed list.`,
    examples: [
      { input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]", stdin: "[1,2,3,4,5]" },
      { input: "head = [1,2]", output: "[2,1]", stdin: "[1,2]" },
      { input: "head = []", output: "[]", stdin: "[]" },
    ],
    constraints: [
      "The number of nodes in the list is the range [0, 5000].",
      "-5000 <= Node.val <= 5000",
    ],
    sol: `def reverseList(head):\n    prev=None; curr=head\n    while curr: nxt=curr.next; curr.next=prev; prev=curr; curr=nxt\n    return prev`,
    note: "Three pointers: prev, curr, next. Reverse each link. O(n), O(1).",
  },
  {
    id: 41,
    title: "Linked List Cycle",
    cat: "Linked List",
    diff: "Easy",
    lc: 141,
    pat: "Fast & Slow Pointers",
    desc: `Given head, the head of a linked list, determine if the linked list has a cycle in it. Return true if there is a cycle in the linked list, otherwise return false.`,
    examples: [
      { input: "head = [3,2,0,-4], pos = 1", output: "true", explanation: "There is a cycle in the linked list, where the tail connects to the 1st node (0-indexed).", stdin: "[3,2,0,-4]\n1" },
      { input: "head = [1,2], pos = 0", output: "true", explanation: "There is a cycle in the linked list, where the tail connects to the 0th node.", stdin: "[1,2]\n0" },
      { input: "head = [1], pos = -1", output: "false", explanation: "There is no cycle in the linked list.", stdin: "[1]\n-1" },
    ],
    constraints: [
      "The number of the nodes in the list is in the range [0, 10^4].",
      "-10^5 <= Node.val <= 10^5",
      "pos is -1 or a valid index in the linked-list.",
    ],
    sol: `def hasCycle(head):\n    s=f=head\n    while f and f.next:\n        s=s.next; f=f.next.next\n        if s==f: return True\n    return False`,
    note: "Floyd's: fast (2x) meets slow in cycle. Fast hits None=no cycle. O(n), O(1).",
  },
  {
    id: 42,
    title: "Merge Two Sorted Lists",
    cat: "Linked List",
    diff: "Easy",
    lc: 21,
    pat: "Linked List",
    desc: `You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists. Return the head of the merged linked list.`,
    examples: [
      { input: "list1 = [1,2,4], list2 = [1,3,4]", output: "[1,1,2,3,4,4]", stdin: "[1,2,4]\n[1,3,4]" },
      { input: "list1 = [], list2 = []", output: "[]", stdin: "[]\n[]" },
      { input: "list1 = [], list2 = [0]", output: "[0]", stdin: "[]\n[0]" },
    ],
    constraints: [
      "The number of nodes in both lists is in the range [0, 50].",
      "-100 <= Node.val <= 100",
      "Both list1 and list2 are sorted in non-decreasing order.",
    ],
    sol: `def mergeTwoLists(l1,l2):\n    d=cur=ListNode()\n    while l1 and l2:\n        if l1.val<=l2.val: cur.next=l1; l1=l1.next\n        else: cur.next=l2; l2=l2.next\n        cur=cur.next\n    cur.next=l1 or l2\n    return d.next`,
    note: "Dummy head simplifies edge cases. Append remainder. O(n+m).",
  },
  {
    id: 43,
    title: "Merge K Sorted Lists",
    cat: "Linked List",
    diff: "Hard",
    lc: 23,
    pat: "Heap",
    desc: `You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.`,
    examples: [
      { input: "lists = [[1,4,5],[1,3,4],[2,6]]", output: "[1,1,2,3,4,4,5,6]", stdin: "[[1,4,5],[1,3,4],[2,6]]" },
      { input: "lists = []", output: "[]", stdin: "[]" },
      { input: "lists = [[]]", output: "[]", stdin: "[[]]" },
    ],
    constraints: [
      "k == lists.length",
      "0 <= k <= 10^4",
      "0 <= lists[i].length <= 500",
      "-10^4 <= lists[i][j] <= 10^4",
      "lists[i] is sorted in ascending order.",
    ],
    sol: `import heapq\ndef mergeKLists(lists):\n    h=[]\n    for i,l in enumerate(lists):\n        if l: heapq.heappush(h,(l.val,i,l))\n    d=cur=ListNode()\n    while h:\n        v,i,n=heapq.heappop(h); cur.next=n; cur=cur.next\n        if n.next: heapq.heappush(h,(n.next.val,i,n.next))\n    return d.next`,
    note: "Min-heap of (val,idx,node). Pop min, push its next. O(N log k).",
  },
  {
    id: 44,
    title: "Remove Nth Node From End",
    cat: "Linked List",
    diff: "Medium",
    lc: 19,
    pat: "Fast & Slow Pointers",
    desc: `Given the head of a linked list, remove the nth node from the end of the list and return its head. Do it in one pass.`,
    examples: [
      { input: "head = [1,2,3,4,5], n = 2", output: "[1,2,3,5]", stdin: "[1,2,3,4,5]\n2" },
      { input: "head = [1], n = 1", output: "[]", stdin: "[1]\n1" },
      { input: "head = [1,2], n = 1", output: "[1]", stdin: "[1,2]\n1" },
    ],
    constraints: [
      "The number of nodes in the list is sz.",
      "1 <= sz <= 30",
      "0 <= Node.val <= 100",
      "1 <= n <= sz",
    ],
    sol: `def removeNthFromEnd(head,n):\n    d=ListNode(0,head); l=d; r=head\n    for _ in range(n): r=r.next\n    while r: l=l.next; r=r.next\n    l.next=l.next.next\n    return d.next`,
    note: "Offset r by n. Move both until r=None. l.next is target. O(n).",
  },
  {
    id: 45,
    title: "Reorder List",
    cat: "Linked List",
    diff: "Medium",
    lc: 143,
    pat: "Linked List",
    desc: `You are given the head of a singly linked-list. Reorder it such that the nodes are rearranged as: L0 → Ln → L1 → Ln-1 → L2 → Ln-2 → ... You may not modify the values in the list's nodes. Only nodes themselves may be changed.`,
    examples: [
      { input: "head = [1,2,3,4]", output: "[1,4,2,3]", stdin: "[1,2,3,4]" },
      { input: "head = [1,2,3,4,5]", output: "[1,5,2,4,3]", stdin: "[1,2,3,4,5]" },
    ],
    constraints: [
      "The number of nodes in the list is in the range [1, 5 * 10^4].",
      "1 <= Node.val <= 1000",
    ],
    sol: `def reorderList(head):\n    s,f=head,head.next\n    while f and f.next: s=s.next; f=f.next.next\n    sec=s.next; s.next=None; prev=None\n    while sec: nxt=sec.next; sec.next=prev; prev=sec; sec=nxt\n    f1,f2=head,prev\n    while f2: t1,t2=f1.next,f2.next; f1.next=f2; f2.next=t1; f1,f2=t1,t2`,
    note: "3 steps: find mid, reverse 2nd half, interleave. O(n), O(1).",
  },
  {
    id: 46,
    title: "Set Matrix Zeroes",
    cat: "Matrix",
    diff: "Medium",
    lc: 73,
    pat: "Matrix",
    desc: `Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0's. You must do it in place.`,
    examples: [
      { input: "matrix = [[1,1,1],[1,0,1],[1,1,1]]", output: "[[1,0,1],[0,0,0],[1,0,1]]", stdin: "[[1,1,1],[1,0,1],[1,1,1]]" },
      { input: "matrix = [[0,1,2,0],[3,4,5,2],[1,3,1,5]]", output: "[[0,0,0,0],[0,4,5,0],[0,3,1,0]]", stdin: "[[0,1,2,0],[3,4,5,2],[1,3,1,5]]" },
    ],
    constraints: [
      "m == matrix.length",
      "n == matrix[0].length",
      "1 <= m, n <= 200",
      "-2^31 <= matrix[i][j] <= 2^31 - 1",
    ],
    sol: `def setZeroes(m):\n    R,C=len(m),len(m[0])\n    rz=any(m[0][c]==0 for c in range(C))\n    for r in range(1,R):\n        for c in range(C):\n            if m[r][c]==0: m[0][c]=0; m[r][0]=0\n    for r in range(1,R):\n        for c in range(1,C):\n            if m[0][c]==0 or m[r][0]==0: m[r][c]=0\n    if m[0][0]==0:\n        for r in range(R): m[r][0]=0\n    if rz:\n        for c in range(C): m[0][c]=0`,
    note: "First row/col as markers. Handle first row separately. O(m×n), O(1).",
  },
  {
    id: 47,
    title: "Spiral Matrix",
    cat: "Matrix",
    diff: "Medium",
    lc: 54,
    pat: "Matrix",
    desc: `Given an m x n matrix, return all elements of the matrix in spiral order.`,
    examples: [
      { input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]", stdin: "[[1,2,3],[4,5,6],[7,8,9]]" },
      { input: "matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]", output: "[1,2,3,4,8,12,11,10,9,5,6,7]", stdin: "[[1,2,3,4],[5,6,7,8],[9,10,11,12]]" },
    ],
    constraints: [
      "m == matrix.length",
      "n == matrix[i].length",
      "1 <= m, n <= 10",
      "-100 <= matrix[i][j] <= 100",
    ],
    sol: `def spiralOrder(m):\n    res=[]; l,r,t,b=0,len(m[0])-1,0,len(m)-1\n    while l<=r and t<=b:\n        for c in range(l,r+1): res.append(m[t][c])\n        t+=1\n        for row in range(t,b+1): res.append(m[row][r])\n        r-=1\n        if t<=b:\n            for c in range(r,l-1,-1): res.append(m[b][c])\n            b-=1\n        if l<=r:\n            for row in range(b,t-1,-1): res.append(m[row][l])\n            l+=1\n    return res`,
    note: "Four boundaries shrink inward. O(m×n).",
  },
  {
    id: 48,
    title: "Rotate Image",
    cat: "Matrix",
    diff: "Medium",
    lc: 48,
    pat: "Matrix",
    desc: `You are given an n x n 2D matrix representing an image. Rotate the image by 90 degrees clockwise. You have to rotate the image in-place, which means you have to modify the input 2D matrix directly.`,
    examples: [
      { input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[[7,4,1],[8,5,2],[9,6,3]]", stdin: "[[1,2,3],[4,5,6],[7,8,9]]" },
      { input: "matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]", output: "[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]", stdin: "[[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]" },
    ],
    constraints: [
      "n == matrix.length == matrix[i].length",
      "1 <= n <= 20",
      "-1000 <= matrix[i][j] <= 1000",
    ],
    sol: `def rotate(m):\n    n=len(m)\n    for i in range(n):\n        for j in range(i+1,n): m[i][j],m[j][i]=m[j][i],m[i][j]\n    for row in m: row.reverse()`,
    note: "Transpose then reverse each row = 90° CW. In-place, O(n²).",
  },
  {
    id: 49,
    title: "Word Search",
    cat: "Matrix",
    diff: "Medium",
    lc: 79,
    pat: "Backtracking",
    desc: `Given an m x n grid of characters board and a string word, return true if word exists in the grid. The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once.`,
    examples: [
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"", output: "true", stdin: "[[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]]\nABCCED" },
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\"", output: "true", stdin: "[[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]]\nSEE" },
      { input: "board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCB\"", output: "false", stdin: "[[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]]\nABCB" },
    ],
    constraints: [
      "m == board.length",
      "n = board[i].length",
      "1 <= m, n <= 6",
      "1 <= word.length <= 15",
      "board and word consists of only lowercase and uppercase English letters.",
    ],
    sol: `def exist(board,word):\n    R,C=len(board),len(board[0]); path=set()\n    def dfs(r,c,i):\n        if i==len(word): return True\n        if r<0 or c<0 or r>=R or c>=C or word[i]!=board[r][c] or (r,c) in path: return False\n        path.add((r,c))\n        res=any(dfs(r+dr,c+dc,i+1) for dr,dc in[(1,0),(-1,0),(0,1),(0,-1)])\n        path.remove((r,c)); return res\n    return any(dfs(r,c,0) for r in range(R) for c in range(C))`,
    note: "DFS + backtracking. path set prevents revisit. Remove on backtrack. O(m×n×4^L).",
  },
  {
    id: 50,
    title: "Longest Substring No Repeat",
    cat: "String",
    diff: "Medium",
    lc: 3,
    pat: "Sliding Window",
    desc: `Given a string s, find the length of the longest substring without repeating characters.`,
    examples: [
      { input: "s = \"abcabcbb\"", output: "3", explanation: "The answer is \"abc\", with the length of 3.", stdin: "abcabcbb" },
      { input: "s = \"bbbbb\"", output: "1", explanation: "The answer is \"b\", with the length of 1.", stdin: "bbbbb" },
      { input: "s = \"pwwkew\"", output: "3", explanation: "The answer is \"wke\", with the length of 3.", stdin: "pwwkew" },
    ],
    constraints: [
      "0 <= s.length <= 5 * 10^4",
      "s consists of English letters, digits, symbols and spaces.",
    ],
    sol: `def lengthOfLongestSubstring(s):\n    cs=set(); l=res=0\n    for r in range(len(s)):\n        while s[r] in cs: cs.remove(s[l]); l+=1\n        cs.add(s[r]); res=max(res,r-l+1)\n    return res`,
    note: "Sliding window. Shrink left when duplicate found. O(n).",
  },
  {
    id: 51,
    title: "Longest Repeating Char Replacement",
    cat: "String",
    diff: "Medium",
    lc: 424,
    pat: "Sliding Window",
    desc: `You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times. Return the length of the longest substring containing the same letter you can get after performing the above operations.`,
    examples: [
      { input: "s = \"ABAB\", k = 2", output: "4", explanation: "Replace the two 'A's with two 'B's or vice versa.", stdin: "ABAB\n2" },
      { input: "s = \"AABABBA\", k = 1", output: "4", explanation: "Replace the one 'A' in the middle with 'B' and form \"AABBBBA\". The substring \"BBBB\" has the longest repeating letters.", stdin: "AABABBA\n1" },
    ],
    constraints: [
      "1 <= s.length <= 10^5",
      "s consists of only uppercase English letters.",
      "0 <= k <= s.length",
    ],
    sol: `def characterReplacement(s,k):\n    cnt={}; res=l=0\n    for r in range(len(s)):\n        cnt[s[r]]=cnt.get(s[r],0)+1\n        while (r-l+1)-max(cnt.values())>k: cnt[s[l]]-=1; l+=1\n        res=max(res,r-l+1)\n    return res`,
    note: "(window_size - max_freq) ≤ k = valid. O(n×26)=O(n).",
  },
  {
    id: 52,
    title: "Minimum Window Substring",
    cat: "String",
    diff: "Hard",
    lc: 76,
    pat: "Sliding Window",
    desc: `Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string "".`,
    examples: [
      { input: "s = \"ADOBECODEBANC\", t = \"ABC\"", output: "\"BANC\"", explanation: "The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t.", stdin: "ADOBECODEBANC\nABC" },
      { input: "s = \"a\", t = \"a\"", output: "\"a\"", explanation: "The entire string s is the minimum window.", stdin: "a\na" },
      { input: "s = \"a\", t = \"aa\"", output: "\"\"", explanation: "Both 'a's from t must be included in the window. Since the largest window of s only has one 'a', return empty string.", stdin: "a\naa" },
    ],
    constraints: [
      "m == s.length",
      "n == t.length",
      "1 <= m, n <= 10^5",
      "s and t consist of uppercase and lowercase English letters.",
    ],
    sol: `def minWindow(s,t):\n    if not t: return ''\n    ct,w={},{}\n    for c in t: ct[c]=ct.get(c,0)+1\n    have=need=len(ct); res=[-1,-1]; rl=float('inf'); l=0\n    for r in range(len(s)):\n        c=s[r]; w[c]=w.get(c,0)+1\n        if c in ct and w[c]==ct[c]: have-=1\n        while have==0:\n            if r-l+1<rl: rl=r-l+1; res=[l,r]\n            w[s[l]]-=1\n            if s[l] in ct and w[s[l]]<ct[s[l]]: have+=1\n            l+=1\n    l,r=res; return s[l:r+1] if rl!=float('inf') else ''`,
    note: "have/need counters. Expand right, shrink left while valid. O(n+m).",
  },
  {
    id: 53,
    title: "Valid Anagram",
    cat: "String",
    diff: "Easy",
    lc: 242,
    pat: "Hash Map",
    desc: `Given two strings s and t, return true if t is an anagram of s, and false otherwise. An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, using all the original letters exactly once.`,
    examples: [
      { input: "s = \"anagram\", t = \"nagaram\"", output: "true", stdin: "anagram\nnagaram" },
      { input: "s = \"rat\", t = \"car\"", output: "false", stdin: "rat\ncar" },
    ],
    constraints: [
      "1 <= s.length, t.length <= 5 * 10^4",
      "s and t consist of lowercase English letters.",
    ],
    sol: `from collections import Counter\ndef isAnagram(s,t): return len(s)==len(t) and Counter(s)==Counter(t)`,
    note: "Counter compares char frequencies. O(n).",
  },
  {
    id: 54,
    title: "Group Anagrams",
    cat: "String",
    diff: "Medium",
    lc: 49,
    pat: "Hash Map",
    desc: `Given an array of strings strs, group the anagrams together. You can return the answer in any order. An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, using all the original letters exactly once.`,
    examples: [
      { input: "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", output: "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]", stdin: "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]" },
      { input: "strs = [\"\"]", output: "[[\"\"]]", stdin: "[\"\"]" },
      { input: "strs = [\"a\"]", output: "[[\"a\"]]", stdin: "[\"a\"]" },
    ],
    constraints: [
      "1 <= strs.length <= 10^4",
      "0 <= strs[i].length <= 100",
      "strs[i] consists of lowercase English letters.",
    ],
    sol: `from collections import defaultdict\ndef groupAnagrams(strs):\n    ans=defaultdict(list)\n    for s in strs:\n        k=[0]*26\n        for c in s: k[ord(c)-97]+=1\n        ans[tuple(k)].append(s)\n    return list(ans.values())`,
    note: "Key=char freq tuple (26 ints). Groups without sorting. O(n×m).",
  },
  {
    id: 55,
    title: "Valid Parentheses",
    cat: "String",
    diff: "Easy",
    lc: 20,
    pat: "Stack",
    desc: `Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid. An input string is valid if open brackets are closed by the same type of brackets and in the correct order, and every close bracket has a corresponding open bracket of the same type.`,
    examples: [
      { input: "s = \"()\"", output: "true", stdin: "()" },
      { input: "s = \"()[]{}\"", output: "true", stdin: "()[]{}" },
      { input: "s = \"(]\"", output: "false", stdin: "(]" },
    ],
    constraints: [
      "1 <= s.length <= 10^4",
      "s consists of parentheses only '()[]{}'.",
    ],
    sol: `def isValid(s):\n    st=[]; m={')':'(',']':'[','}':'{'}\n    for c in s:\n        if c in m:\n            if not st or st[-1]!=m[c]: return False\n            st.pop()\n        else: st.append(c)\n    return not st`,
    note: "Push open brackets. On close, check stack top. O(n).",
  },
  {
    id: 56,
    title: "Valid Palindrome",
    cat: "String",
    diff: "Easy",
    lc: 125,
    pat: "Two Pointers",
    desc: `A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Given a string s, return true if it is a palindrome, or false otherwise.`,
    examples: [
      { input: "s = \"A man, a plan, a canal: Panama\"", output: "true", explanation: "\"amanaplanacanalpanama\" is a palindrome.", stdin: "A man, a plan, a canal: Panama" },
      { input: "s = \"race a car\"", output: "false", explanation: "\"raceacar\" is not a palindrome.", stdin: "race a car" },
      { input: "s = \" \"", output: "true", explanation: "s is an empty string \"\" after removing non-alphanumeric characters. Since an empty string reads the same forward and backward, it is a palindrome.", stdin: " " },
    ],
    constraints: [
      "1 <= s.length <= 2 * 10^5",
      "s consists only of printable ASCII characters.",
    ],
    sol: `def isPalindrome(s):\n    l,r=0,len(s)-1\n    while l<r:\n        while l<r and not s[l].isalnum(): l+=1\n        while l<r and not s[r].isalnum(): r-=1\n        if s[l].lower()!=s[r].lower(): return False\n        l+=1; r-=1\n    return True`,
    note: "Two pointers, skip non-alphanumeric inline. O(n), O(1).",
  },
  {
    id: 57,
    title: "Longest Palindromic Substring",
    cat: "String",
    diff: "Medium",
    lc: 5,
    pat: "Two Pointers",
    desc: `Given a string s, return the longest palindromic substring in s.`,
    examples: [
      { input: "s = \"babad\"", output: "\"bab\"", explanation: "\"aba\" is also a valid answer.", stdin: "babad" },
      { input: "s = \"cbbd\"", output: "\"bb\"", stdin: "cbbd" },
    ],
    constraints: [
      "1 <= s.length <= 1000",
      "s consist of only digits and English letters.",
    ],
    sol: `def longestPalindrome(s):\n    res=''\n    for i in range(len(s)):\n        for l,r in[(i,i),(i,i+1)]:\n            while l>=0 and r<len(s) and s[l]==s[r]:\n                if r-l+1>len(res): res=s[l:r+1]\n                l-=1; r+=1\n    return res`,
    note: "Expand around center. Odd+even. O(n²), O(1).",
  },
  {
    id: 58,
    title: "Palindromic Substrings",
    cat: "String",
    diff: "Medium",
    lc: 647,
    pat: "Two Pointers",
    desc: `Given a string s, return the number of palindromic substrings in it. A string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.`,
    examples: [
      { input: "s = \"abc\"", output: "3", explanation: "Three palindromic strings: \"a\", \"b\", \"c\".", stdin: "abc" },
      { input: "s = \"aaa\"", output: "6", explanation: "Six palindromic strings: \"a\", \"a\", \"a\", \"aa\", \"aa\", \"aaa\".", stdin: "aaa" },
    ],
    constraints: [
      "1 <= s.length <= 1000",
      "s consists of lowercase English letters.",
    ],
    sol: `def countSubstrings(s):\n    cnt=0\n    for i in range(len(s)):\n        for l,r in[(i,i),(i,i+1)]:\n            while l>=0 and r<len(s) and s[l]==s[r]: cnt+=1; l-=1; r+=1\n    return cnt`,
    note: "Expand around center, count each expansion. O(n²).",
  },
  {
    id: 59,
    title: "Encode and Decode Strings",
    cat: "String",
    diff: "Medium",
    lc: 271,
    pat: "String Encoding",
    desc: `Design an algorithm to encode a list of strings to a single string. The encoded string is then sent over the network and is decoded back to the original list of strings. Implement encode and decode functions that are inverse of each other. The encoded string should be decodable to the original list of strings without needing any additional information.`,
    examples: [
      { input: "strs = [\"lint\",\"code\",\"love\",\"you\"]", output: "[\"lint\",\"code\",\"love\",\"you\"]", explanation: "One possible encode method is: \"4#lint4#code4#love3#you\"", stdin: "[\"lint\",\"code\",\"love\",\"you\"]" },
      { input: "strs = [\"we\",\"say\",\":\",\"yes\"]", output: "[\"we\",\"say\",\":\",\"yes\"]", stdin: "[\"we\",\"say\",\":\",\"yes\"]" },
    ],
    constraints: [
      "1 <= strs.length <= 200",
      "0 <= strs[i].length <= 200",
      "strs[i] contains any possible characters out of 256 valid ASCII characters.",
    ],
    sol: `def encode(strs): return ''.join(f'{len(s)}#{s}' for s in strs)\ndef decode(s):\n    res=[]; i=0\n    while i<len(s):\n        j=s.index('#',i); n=int(s[i:j])\n        res.append(s[j+1:j+1+n]); i=j+1+n\n    return res`,
    note: "Length-prefix '4#word'. Handles any chars. O(n).",
  },
  {
    id: 60,
    title: "Maximum Depth of Binary Tree",
    cat: "Tree",
    diff: "Easy",
    lc: 104,
    pat: "DFS",
    desc: `Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.`,
    examples: [
      { input: "root = [3,9,20,null,null,15,7]", output: "3", stdin: "[3,9,20,null,null,15,7]" },
      { input: "root = [1,null,2]", output: "2", stdin: "[1,null,2]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [0, 10^4].",
      "-100 <= Node.val <= 100",
    ],
    sol: `def maxDepth(root):\n    if not root: return 0\n    return 1+max(maxDepth(root.left),maxDepth(root.right))`,
    note: "1 + max(left,right). Recursive. O(n).",
  },
  {
    id: 61,
    title: "Same Tree",
    cat: "Tree",
    diff: "Easy",
    lc: 100,
    pat: "DFS",
    desc: `Given the roots of two binary trees p and q, write a function to check if they are the same or not. Two binary trees are considered the same if they are structurally identical, and the nodes have the same value.`,
    examples: [
      { input: "p = [1,2,3], q = [1,2,3]", output: "true", stdin: "[1,2,3]\n[1,2,3]" },
      { input: "p = [1,2], q = [1,null,2]", output: "false", stdin: "[1,2]\n[1,null,2]" },
      { input: "p = [1,2,1], q = [1,1,2]", output: "false", stdin: "[1,2,1]\n[1,1,2]" },
    ],
    constraints: [
      "The number of nodes in both trees is in the range [0, 100].",
      "-10^4 <= Node.val <= 10^4",
    ],
    sol: `def isSameTree(p,q):\n    if not p and not q: return True\n    if not p or not q or p.val!=q.val: return False\n    return isSameTree(p.left,q.left) and isSameTree(p.right,q.right)`,
    note: "Both null=True, one null=False, diff val=False. Recurse. O(n).",
  },
  {
    id: 62,
    title: "Invert Binary Tree",
    cat: "Tree",
    diff: "Easy",
    lc: 226,
    pat: "DFS",
    desc: `Given the root of a binary tree, invert the tree, and return its root.`,
    examples: [
      { input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]", stdin: "[4,2,7,1,3,6,9]" },
      { input: "root = [2,1,3]", output: "[2,3,1]", stdin: "[2,1,3]" },
      { input: "root = []", output: "[]", stdin: "[]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [0, 100].",
      "-100 <= Node.val <= 100",
    ],
    sol: `def invertTree(root):\n    if not root: return None\n    root.left,root.right=invertTree(root.right),invertTree(root.left)\n    return root`,
    note: "Swap children, recursively invert. O(n).",
  },
  {
    id: 63,
    title: "Binary Tree Maximum Path Sum",
    cat: "Tree",
    diff: "Hard",
    lc: 124,
    pat: "DFS",
    desc: `A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. The path does not need to pass through the root. Given the root of a binary tree, return the maximum path sum of any non-empty path.`,
    examples: [
      { input: "root = [1,2,3]", output: "6", explanation: "The optimal path is 2 -> 1 -> 3 with a path sum of 2 + 1 + 3 = 6.", stdin: "[1,2,3]" },
      { input: "root = [-10,9,20,null,null,15,7]", output: "42", explanation: "The optimal path is 15 -> 20 -> 7 with a path sum of 15 + 20 + 7 = 42.", stdin: "[-10,9,20,null,null,15,7]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [1, 3 * 10^4].",
      "-1000 <= Node.val <= 1000",
    ],
    sol: `def maxPathSum(root):\n    res=[root.val]\n    def dfs(r):\n        if not r: return 0\n        l=max(dfs(r.left),0); ri=max(dfs(r.right),0)\n        res[0]=max(res[0],r.val+l+ri)\n        return r.val+max(l,ri)\n    dfs(root); return res[0]`,
    note: "At each node: candidate=node+left+right. Return node+max(one side) up. O(n).",
  },
  {
    id: 64,
    title: "Binary Tree Level Order Traversal",
    cat: "Tree",
    diff: "Medium",
    lc: 102,
    pat: "BFS",
    desc: `Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).`,
    examples: [
      { input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", stdin: "[3,9,20,null,null,15,7]" },
      { input: "root = [1]", output: "[[1]]", stdin: "[1]" },
      { input: "root = []", output: "[]", stdin: "[]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [0, 2000].",
      "-1000 <= Node.val <= 1000",
    ],
    sol: `from collections import deque\ndef levelOrder(root):\n    res=[]; q=deque([root]) if root else deque()\n    while q:\n        lvl=[]\n        for _ in range(len(q)):\n            n=q.popleft(); lvl.append(n.val)\n            if n.left: q.append(n.left)\n            if n.right: q.append(n.right)\n        res.append(lvl)\n    return res`,
    note: "BFS with deque. Snapshot len(q) at level start. O(n).",
  },
  {
    id: 65,
    title: "Serialize and Deserialize Binary Tree",
    cat: "Tree",
    diff: "Hard",
    lc: 297,
    pat: "DFS",
    desc: `Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer, or transmitted across a network. Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work — just ensure that a binary tree can be serialized to a string and this string can be deserialized to the original tree structure.`,
    examples: [
      { input: "root = [1,2,3,null,null,4,5]", output: "[1,2,3,null,null,4,5]", explanation: "Serialize to a string then deserialize back to the original tree.", stdin: "[1,2,3,null,null,4,5]" },
      { input: "root = []", output: "[]", stdin: "[]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [0, 10^4].",
      "-1000 <= Node.val <= 1000",
    ],
    sol: `def serialize(root):\n    res=[]\n    def dfs(n):\n        if not n: res.append('N'); return\n        res.append(str(n.val)); dfs(n.left); dfs(n.right)\n    dfs(root); return ','.join(res)\ndef deserialize(data):\n    v=iter(data.split(','))\n    def dfs():\n        x=next(v)\n        if x=='N': return None\n        n=TreeNode(int(x)); n.left=dfs(); n.right=dfs(); return n\n    return dfs()`,
    note: "Pre-order DFS. 'N' marks null. Iterator naturally follows order. O(n).",
  },
  {
    id: 66,
    title: "Subtree of Another Tree",
    cat: "Tree",
    diff: "Easy",
    lc: 572,
    pat: "DFS",
    desc: `Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values as subRoot, and false otherwise. A subtree of a binary tree is a tree that consists of a node in the tree and all of its descendants.`,
    examples: [
      { input: "root = [3,4,5,1,2], subRoot = [4,1,2]", output: "true", stdin: "[3,4,5,1,2]\n[4,1,2]" },
      { input: "root = [3,4,5,1,2,null,null,null,null,0], subRoot = [4,1,2]", output: "false", stdin: "[3,4,5,1,2,null,null,null,null,0]\n[4,1,2]" },
    ],
    constraints: [
      "The number of nodes in the root tree is in the range [1, 2000].",
      "The number of nodes in the subRoot tree is in the range [1, 1000].",
      "-10^4 <= root.val <= 10^4",
      "-10^4 <= subRoot.val <= 10^4",
    ],
    sol: `def isSubtree(s,t):\n    def same(a,b):\n        if not a and not b: return True\n        if not a or not b or a.val!=b.val: return False\n        return same(a.left,b.left) and same(a.right,b.right)\n    if not t: return True\n    if not s: return False\n    return same(s,t) or isSubtree(s.left,t) or isSubtree(s.right,t)`,
    note: "At each node check same(). O(m×n).",
  },
  {
    id: 67,
    title: "Construct BT from Preorder/Inorder",
    cat: "Tree",
    diff: "Medium",
    lc: 105,
    pat: "DFS",
    desc: `Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.`,
    examples: [
      { input: "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]", output: "[3,9,20,null,null,15,7]", stdin: "[3,9,20,15,7]\n[9,3,15,20,7]" },
      { input: "preorder = [-1], inorder = [-1]", output: "[-1]", stdin: "[-1]\n[-1]" },
    ],
    constraints: [
      "1 <= preorder.length <= 3000",
      "inorder.length == preorder.length",
      "-3000 <= preorder[i], inorder[i] <= 3000",
      "preorder and inorder consist of unique values.",
      "Each value of inorder also appears in preorder.",
    ],
    sol: `def buildTree(pre,ino):\n    if not pre or not ino: return None\n    r=TreeNode(pre[0]); m=ino.index(pre[0])\n    r.left=buildTree(pre[1:m+1],ino[:m])\n    r.right=buildTree(pre[m+1:],ino[m+1:])\n    return r`,
    note: "pre[0]=root. Find in inorder to split subtrees. O(n²) naive, O(n) with hashmap.",
  },
  {
    id: 68,
    title: "Validate Binary Search Tree",
    cat: "Tree",
    diff: "Medium",
    lc: 98,
    pat: "DFS",
    desc: `Given the root of a binary tree, determine if it is a valid binary search tree (BST). A valid BST is defined as follows: the left subtree of a node contains only nodes with keys less than the node's key; the right subtree of a node contains only nodes with keys greater than the node's key; both the left and right subtrees must also be binary search trees.`,
    examples: [
      { input: "root = [2,1,3]", output: "true", stdin: "[2,1,3]" },
      { input: "root = [5,1,4,null,null,3,6]", output: "false", explanation: "The root node's value is 5 but its right child's value is 4.", stdin: "[5,1,4,null,null,3,6]" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [1, 10^4].",
      "-2^31 <= Node.val <= 2^31 - 1",
    ],
    sol: `def isValidBST(root):\n    def v(n,lo,hi):\n        if not n: return True\n        if not (lo<n.val<hi): return False\n        return v(n.left,lo,n.val) and v(n.right,n.val,hi)\n    return v(root,float('-inf'),float('inf'))`,
    note: "Pass valid range down. Each node strictly within. O(n).",
  },
  {
    id: 69,
    title: "Kth Smallest Element in BST",
    cat: "Tree",
    diff: "Medium",
    lc: 230,
    pat: "DFS",
    desc: `Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.`,
    examples: [
      { input: "root = [3,1,4,null,2], k = 1", output: "1", stdin: "[3,1,4,null,2]\n1" },
      { input: "root = [5,3,6,2,4,null,null,1], k = 3", output: "3", stdin: "[5,3,6,2,4,null,null,1]\n3" },
    ],
    constraints: [
      "The number of nodes in the tree is n.",
      "1 <= k <= n <= 10^4",
      "0 <= Node.val <= 10^4",
    ],
    sol: `def kthSmallest(root,k):\n    st=[]; c=root\n    while True:\n        while c: st.append(c); c=c.left\n        c=st.pop(); k-=1\n        if k==0: return c.val\n        c=c.right`,
    note: "Iterative in-order = sorted. Return at k=0. O(h+k).",
  },
  {
    id: 70,
    title: "Lowest Common Ancestor of BST",
    cat: "Tree",
    diff: "Medium",
    lc: 235,
    pat: "DFS",
    desc: `Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST. The LCA is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).`,
    examples: [
      { input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", output: "6", explanation: "The LCA of nodes 2 and 8 is 6.", stdin: "[6,2,8,0,4,7,9,null,null,3,5]\n2\n8" },
      { input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4", output: "2", explanation: "The LCA of nodes 2 and 4 is 2, since a node can be a descendant of itself according to the LCA definition.", stdin: "[6,2,8,0,4,7,9,null,null,3,5]\n2\n4" },
      { input: "root = [2,1], p = 2, q = 1", output: "2", stdin: "[2,1]\n2\n1" },
    ],
    constraints: [
      "The number of nodes in the tree is in the range [2, 10^5].",
      "-10^9 <= Node.val <= 10^9",
      "All Node.val are unique.",
      "p != q",
      "p and q will exist in the BST.",
    ],
    sol: `def lowestCommonAncestor(root,p,q):\n    c=root\n    while c:\n        if p.val>c.val and q.val>c.val: c=c.right\n        elif p.val<c.val and q.val<c.val: c=c.left\n        else: return c`,
    note: "Both>cur→right, both<cur→left, split=LCA. O(h).",
  },
  {
    id: 71,
    title: "Implement Trie",
    cat: "Tree",
    diff: "Medium",
    lc: 208,
    pat: "Trie",
    desc: `A trie (pronounced as "try") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. Implement the Trie class with insert(word), search(word), and startsWith(prefix) operations.`,
    examples: [
      { input: "operations = [\"Trie\",\"insert\",\"search\",\"search\",\"startsWith\",\"insert\",\"search\"], values = [[],[\"apple\"],[\"apple\"],[\"app\"],[\"app\"],[\"app\"],[\"app\"]]", output: "[null,null,true,false,true,null,true]", stdin: "[\"Trie\",\"insert\",\"search\",\"search\",\"startsWith\",\"insert\",\"search\"]\n[[],[\"apple\"],[\"apple\"],[\"app\"],[\"app\"],[\"app\"],[\"app\"]]" },
    ],
    constraints: [
      "1 <= word.length, prefix.length <= 2000",
      "word and prefix consist only of lowercase English letters.",
      "At most 3 * 10^4 calls in total will be made to insert, search, and startsWith.",
    ],
    sol: `class TrieNode:\n    def __init__(self): self.c={}; self.end=False\nclass Trie:\n    def __init__(self): self.r=TrieNode()\n    def insert(self,w):\n        n=self.r\n        for c in w:\n            if c not in n.c: n.c[c]=TrieNode()\n            n=n.c[c]\n        n.end=True\n    def search(self,w):\n        n=self.r\n        for c in w:\n            if c not in n.c: return False\n            n=n.c[c]\n        return n.end\n    def startsWith(self,p):\n        n=self.r\n        for c in p:\n            if c not in n.c: return False\n            n=n.c[c]\n        return True`,
    note: "Each node: children dict + end flag. All ops O(m).",
  },
  {
    id: 72,
    title: "Design Add and Search Words",
    cat: "Tree",
    diff: "Medium",
    lc: 211,
    pat: "Trie",
    desc: `Design a data structure that supports adding new words and finding if a string matches any previously added string. Implement the WordDictionary class with addWord(word) and search(word) functions, where search may contain dots '.' which can match any letter.`,
    examples: [
      { input: "operations = [\"WordDictionary\",\"addWord\",\"addWord\",\"addWord\",\"search\",\"search\",\"search\",\"search\"], values = [[],[\"bad\"],[\"dad\"],[\"mad\"],[\"pad\"],[\"bad\"],[\".ad\"],[\"b..\"]]", output: "[null,null,null,null,false,true,true,true]", stdin: "[\"WordDictionary\",\"addWord\",\"addWord\",\"addWord\",\"search\",\"search\",\"search\",\"search\"]\n[[],[\"bad\"],[\"dad\"],[\"mad\"],[\"pad\"],[\"bad\"],[\".ad\"],[\"b..\"]]" },
    ],
    constraints: [
      "1 <= word.length <= 25",
      "word in addWord consists of lowercase English letters.",
      "word in search consist of '.' or lowercase English letters.",
      "There will be at most 2 dots in word for search queries.",
      "At most 10^4 calls will be made to addWord and search.",
    ],
    sol: `class WordDictionary:\n    def __init__(self): self.r=TrieNode()\n    def addWord(self,w):\n        n=self.r\n        for c in w:\n            if c not in n.c: n.c[c]=TrieNode()\n            n=n.c[c]\n        n.end=True\n    def search(self,w):\n        def dfs(i,n):\n            for j in range(i,len(w)):\n                c=w[j]\n                if c=='.':\n                    return any(dfs(j+1,ch) for ch in n.c.values())\n                if c not in n.c: return False\n                n=n.c[c]\n            return n.end\n        return dfs(0,self.r)`,
    note: "Standard Trie + DFS on '.'. Try all children for wildcard. O(26^m) worst.",
  },
  {
    id: 73,
    title: "Word Search II",
    cat: "Tree",
    diff: "Hard",
    lc: 212,
    pat: "Trie + Backtracking",
    desc: `Given an m x n board of characters and a list of strings words, return all words on the board. Each word must be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring. The same letter cell may not be used more than once in a word.`,
    examples: [
      { input: "board = [[\"o\",\"a\",\"a\",\"n\"],[\"e\",\"t\",\"a\",\"e\"],[\"i\",\"h\",\"k\",\"r\"],[\"i\",\"f\",\"l\",\"v\"]], words = [\"oath\",\"pea\",\"eat\",\"rain\"]", output: "[\"eat\",\"oath\"]", stdin: "[[\"o\",\"a\",\"a\",\"n\"],[\"e\",\"t\",\"a\",\"e\"],[\"i\",\"h\",\"k\",\"r\"],[\"i\",\"f\",\"l\",\"v\"]]\n[\"oath\",\"pea\",\"eat\",\"rain\"]" },
      { input: "board = [[\"a\",\"b\"],[\"c\",\"d\"]], words = [\"abcb\"]", output: "[]", stdin: "[[\"a\",\"b\"],[\"c\",\"d\"]]\n[\"abcb\"]" },
    ],
    constraints: [
      "m == board.length",
      "n == board[i].length",
      "1 <= m, n <= 12",
      "board[i][j] is a lowercase English letter.",
      "1 <= words.length <= 3 * 10^4",
    ],
    sol: `def findWords(board,words):\n    class T:\n        def __init__(self): self.c={}; self.end=None\n    r=T()\n    for w in words:\n        n=r\n        for c in w:\n            if c not in n.c: n.c[c]=T()\n            n=n.c[c]\n        n.end=w\n    R,C=len(board),len(board[0]); res=set(); vis=set()\n    def dfs(r,c,n):\n        if r<0 or c<0 or r>=R or c>=C or (r,c) in vis or board[r][c] not in n.c: return\n        vis.add((r,c)); n=n.c[board[r][c]]\n        if n.end: res.add(n.end)\n        for dr,dc in[(1,0),(-1,0),(0,1),(0,-1)]: dfs(r+dr,c+dc,n)\n        vis.remove((r,c))\n    for r in range(R):\n        for c in range(C): dfs(r,c,r)\n    return list(res)`,
    note: "Build Trie. DFS guided by Trie — prune when prefix missing. O(m×n×4^L).",
  },
  {
    id: 74,
    title: "Top K Frequent Elements",
    cat: "Heap",
    diff: "Medium",
    lc: 347,
    pat: "Bucket Sort",
    desc: `Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.`,
    examples: [
      { input: "nums = [1,1,1,2,2,3], k = 2", output: "[1,2]", stdin: "[1,1,1,2,2,3]\n2" },
      { input: "nums = [1], k = 1", output: "[1]", stdin: "[1]\n1" },
    ],
    constraints: [
      "1 <= nums.length <= 10^5",
      "-10^4 <= nums[i] <= 10^4",
      "k is in the range [1, the number of unique elements in the array].",
      "It is guaranteed that the answer is unique.",
    ],
    sol: `def topKFrequent(nums,k):\n    cnt={}; freq=[[] for _ in range(len(nums)+1)]\n    for n in nums: cnt[n]=cnt.get(n,0)+1\n    for n,c in cnt.items(): freq[c].append(n)\n    res=[]\n    for i in range(len(freq)-1,0,-1):\n        for n in freq[i]:\n            res.append(n)\n            if len(res)==k: return res`,
    note: "Bucket sort by freq. Scan R→L. O(n) time and space.",
  },
  {
    id: 75,
    title: "Find Median from Data Stream",
    cat: "Heap",
    diff: "Hard",
    lc: 295,
    pat: "Two Heaps",
    desc: `The median is the middle value in an ordered integer list. If the size of the list is even, there is no middle value, and the median is the mean of the two middle values. Implement the MedianFinder class with addNum(int num) which adds the integer num to the data structure, and findMedian() which returns the median of all elements so far.`,
    examples: [
      { input: "operations = [\"MedianFinder\",\"addNum\",\"addNum\",\"findMedian\",\"addNum\",\"findMedian\"], values = [[],[1],[2],[],[3],[]]", output: "[null,null,null,1.5,null,2.0]", explanation: "After adding 1 and 2, median is (1+2)/2 = 1.5. After adding 3, median is 2.0.", stdin: "[\"MedianFinder\",\"addNum\",\"addNum\",\"findMedian\",\"addNum\",\"findMedian\"]\n[[],[1],[2],[],[3],[]]" },
    ],
    constraints: [
      "-10^5 <= num <= 10^5",
      "There will be at least one element in the data structure before calling findMedian.",
      "At most 5 * 10^4 calls will be made to addNum and findMedian.",
    ],
    sol: `import heapq\nclass MedianFinder:\n    def __init__(self): self.lo=[]; self.hi=[]\n    def addNum(self,n):\n        heapq.heappush(self.lo,-n)\n        if self.lo and self.hi and -self.lo[0]>self.hi[0]:\n            heapq.heappush(self.hi,-heapq.heappop(self.lo))\n        if len(self.lo)>len(self.hi)+1:\n            heapq.heappush(self.hi,-heapq.heappop(self.lo))\n        if len(self.hi)>len(self.lo):\n            heapq.heappush(self.lo,-heapq.heappop(self.hi))\n    def findMedian(self):\n        if len(self.lo)>len(self.hi): return -self.lo[0]\n        return (-self.lo[0]+self.hi[0])/2`,
    note: "Max-heap left, min-heap right. Keep balanced. O(log n) add, O(1) median.",
  },
]

